<!-- Page Heading -->
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Clienti &amp; Fornitori</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a class="btn btn-sm btn-outline-primary" href="<?php echo $baseUrl;?>/records/customersupplier/list" role="button"><i class="fas fa-arrow-left"></i>&nbsp;Back</a>
        </div>
    </div>
</div>

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-user"></i>
        Inserimento Cliente/Fornitore
    </div>
    <div class="card-body">
        <form id="add-customer" data-parsley-validate="">
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label for="inputCode">Code</label>
                    <input type="text" class="form-control" id="inputCode" placeholder="-" disabled>
                </div>
                <div class="form-group col-md-10">
                    <label for="inputName">Nome Azienda</label>
                    <input type="text" class="form-control" id="inputName" placeholder="" data-parsley-minlength="3" autocomplete="off" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputAddress">Indirizzo</label>
                    <input type="text" class="form-control" id="inputAddress" placeholder="" data-parsley-minlength="5" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputCity">Città</label>
                    <input type="text" class="form-control" id="inputCity" placeholder="" data-parsley-minlength="3" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="inputDistrict">Provincia (Sigla)</label>
                    <input type="text" class="form-control" id="inputDistrict" placeholder="" data-parsley-provincia="" required>
                </div>
                <div class="form-group col-md-4">
                    <label for="inputZip">CAP</label>
                    <input type="text" class="form-control" id="inputZip" placeholder="" data-parsley-zip-code="" required>
                </div>
                <div class="form-group col-md-4">
                    <label for="inputCountry">Paese</label>
                    <?php MyUtility::printCountrySelectForm("form-control", "inputCountry", "IT"); ?> 
                </div>
            </div>
            <div class="form-row">
                 <div class="form-group col-md-6">
          	         <label for="inputEmail">Email</label>
                     <input type="email" class="form-control" id="inputEmail" placeholder="" data-parsley-type="email" autocomplete="off" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputWebsite">Website</label>
                    <input type="text" class="form-control" id="inputWebsite" placeholder="http://" data-parsley-type="url" autocomplete="off" required>
                </div>
            </div>
            <div class="form-row">
            <div class="form-group col-md-6">
                    <label for="inputPhone">Telefono</label>
                    <input type="text" class="form-control" id="inputPhone" placeholder="" data-parsley-phone="" autocomplete="off" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputFax">Fax</label>
                    <input type="text" class="form-control" id="inputFax" placeholder="" data-parsley-phone="" autocomplete="off">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputVAT">P. IVA</label>
                    <input type="text" class="form-control" id="inputVAT" placeholder="" data-parsley-vat="" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputNIN">Codice Fiscale</label>
                    <input type="text" class="form-control" id="inputNIN" placeholder="" data-parsley-ninsupplier="" required>
                </div>
            </div>
            <div class="form-group">
                <label for="inputIBAN">IBAN</label>
                <input type="text" class="form-control" id="inputIBAN" placeholder="" data-parsley-iban="">
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <div class="btn-group-toggle"  data-toggle="buttons">
                        <label class="btn btn-primary form-check-label">
                            <input class="form-check-input" type="checkbox" autocomplete="off" id="inputCustomerCheck"> 
                            <span>Cliente</span>
                        </label>
                        <label class="btn btn-primary form-check-label">
                            <input class="form-check-input" type="checkbox" autocomplete="off" id="inputSupplierCheck">
                            <span>Fornitore</span>
                        </label>
                        <label class="btn btn-primary form-check-label">
                            <input class="form-check-input" type="checkbox" autocomplete="off" id="inputPrivateCheck">
                            <span>Privato</span>
                        </label>
                    </div>
            <!--
                <div class="form-group col-md-2">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="inputCustomerCheck">
                        <label class="custom-control-label" for="inputCustomerCheck">Cliente</label>
                    </div>
                </div>
                <div class="form-group col-md-2">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="inputSupplierCheck">
                        <label class="custom-control-label" for="inputSupplierCheck">Fornitore</label>
                    </div>
                </div>
                <div class="form-group col-md-2">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="inputPrivateCheck">
                        <label class="custom-control-label" for="inputPrivateCheck">Privato</label>
                    </div>
                </div>-->
                </div>
                <div class="form-group col-md-6">&nbsp;
                </div>
            </div>
            <div class="form-group">
                <label for="inputNote">Note</label>
                <textarea class="form-control" id="inputNote" rows="3" placeholder="Note">
                </textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit" id="add-customer-save">Save</button>
                <button class="btn btn-primary" type="reset" id="add-customer-reset">Reset</button>
            </div>

            <div class="alert alert-success d-none" role="alert" id="add-customer-success">
                <i class="fas fa-check"></i>&nbsp;New customer/supplier added with success!
            </div>
            
            <div class="alert alert-danger d-none" role="alert" id="add-customer-error">
			&nbsp;
            </div>
            
            <div class="alert alert-primary d-none" role="alert" id="add-customer-loading">
                <i class="fas fa-spinner fa-spin"></i>&nbsp;Loading...
            </div>
        </form>
    </div>
</div>
