<!-- Page Heading -->
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Clienti &amp; Fornitori</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a class="btn btn-sm btn-outline-primary" href="<?php echo $baseUrl;?>/records/customersupplier/list" role="button"><i class="fas fa-arrow-left"></i>&nbsp;Back</a>
        </div>
    </div>
</div>

<?php

$isError = FALSE;

if ($nav->getResourceId() == 0)
{
    // TODO: print error
}
else 
{
    // Get the user list
    $query = "SELECT * FROM " . PRJ_DB_TABLE_CUSTOMER_SUPPLIER . " WHERE Id={$nav->getResourceId()}";
    $result = $db->query($query);
    if ($result)
    {
        $rows = $result->fetchAll(PDO::FETCH_ASSOC);
        if ((count($rows) == 0) || (count($rows) > 1))
        {
            $isError = TRUE;
        }
    }
    else 
    {
        $isError = TRUE;
    }
}

if ($isError == FALSE)
{
?>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-building"></i>
        Modifica Cliente/Fornitore
    </div>
    <div class="card-body">
        <form id="edit-customer" data-parsley-validate="">
            <input type="hidden" id="inputId" value="<?php echo $rows[0]['Id']; ?>" />
            <div class="form-row">
                <div class="form-group col-md-2">
                    <label for="inputCode">Code</label>
                    <input type="text" class="form-control" id="inputCode" placeholder="<?php echo $rows[0]['Code']; ?>" disabled>
                </div>
                <div class="form-group col-md-10">
                    <label for="inputName">Nome Azienda</label>
                    <input type="text" class="form-control" id="inputName" value="<?php echo $rows[0]['Name']; ?>" data-parsley-minlength="3" autocomplete="off" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputAddress">Indirizzo</label>
                    <input type="text" class="form-control" id="inputAddress" value="<?php echo $rows[0]['Address']; ?>" data-parsley-minlength="5" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputCity">Città</label>
                    <input type="text" class="form-control" id="inputCity" value="<?php echo $rows[0]['City']; ?>" data-parsley-minlength="3" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="inputDistrict">Provincia (Sigla)</label>
                    <input type="text" class="form-control" id="inputDistrict" value="<?php echo $rows[0]['District']; ?>" data-parsley-provincia="" required>
                </div>
                <div class="form-group col-md-4">
                    <label for="inputZip">CAP</label>
                    <input type="text" class="form-control" id="inputZip" value="<?php echo $rows[0]['ZipCode']; ?>" data-parsley-zip-code="" required>
                </div>
                <div class="form-group col-md-4">
                    <label for="inputCountry">Paese</label>
                    <?php MyUtility::printCountrySelectForm("form-control", "inputCountry", $rows[0]['Country']); ?> 
                </div>
            </div>
            <div class="form-row">
                 <div class="form-group col-md-6">
          	         <label for="inputEmail">Email</label>
                     <input type="email" class="form-control" id="inputEmail" value="<?php echo $rows[0]['Email']; ?>" data-parsley-type="email" autocomplete="off" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputWebsite">Website</label>
                    <input type="text" class="form-control" id="inputWebsite" value="<?php echo $rows[0]['Website']; ?>" data-parsley-type="url" autocomplete="off" required>
                </div>
            </div>
            <div class="form-row">
            <div class="form-group col-md-6">
                    <label for="inputPhone">Telefono</label>
                    <input type="text" class="form-control" id="inputPhone" value="<?php echo $rows[0]['Phone']; ?>" data-parsley-phone="" autocomplete="off" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputFax">Fax</label>
                    <input type="text" class="form-control" id="inputFax" value="<?php echo $rows[0]['Fax']; ?>" data-parsley-phone="" autocomplete="off">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputVAT">P. IVA</label>
                    <input type="text" class="form-control" id="inputVAT" value="<?php echo $rows[0]['VATID']; ?>" data-parsley-vat="" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputNIN">Codice Fiscale</label>
                    <input type="text" class="form-control" id="inputNIN" value="<?php echo $rows[0]['NIN']; ?>" data-parsley-ninsupplier="" required>
                </div>
            </div>
            <div class="form-group">
                <label for="inputIBAN">IBAN</label>
                <input type="text" class="form-control" id="inputIBAN" value="<?php echo $rows[0]['IBAN']; ?>" data-parsley-iban="">
            </div>
            <div class="form-row">
                <div class="form-group col-md-1">
                    <label for="inputStatus">Status</label>
                    <div class="btn-group-toggle"  data-toggle="buttons">
                        <label class="btn form-check-label btn-primary <?php if ($rows[0]['Active'] == 1) {echo "active";} ?> ">
                            <input class="form-check-input" type="checkbox" autocomplete="off" id="inputStatus" <?php if ($rows[0]['Active'] == 1) {echo " checked=\"checked\"";} ?>> 
                            <span>Attivo</span>
                        </label>
                    </div>
                </div>
                <div class="form-group col-md-11">
                    <label for="inputCustomerCheck">Opzioni</label>
                    <div class="btn-group-toggle"  data-toggle="buttons">
                        <label class="btn form-check-label btn-primary <?php if ($rows[0]['Customer'] == 1) {echo "active";} ?>">
                            <input class="form-check-input" type="checkbox" autocomplete="off" id="inputCustomerCheck" <?php if ($rows[0]['Customer'] == 1) {echo " checked=\"checked\"";} ?>> 
                            <span>Cliente</span>
                        </label>
                        <label class="btn form-check-label btn-primary <?php if ($rows[0]['Supplier'] == 1) {echo "active";} ?>">
                            <input class="form-check-input" type="checkbox" autocomplete="off" id="inputSupplierCheck" <?php if ($rows[0]['Supplier'] == 1) {echo " checked=\"checked\"";} ?>>
                            <span>Fornitore</span>
                        </label>
                        <label class="btn form-check-label btn-primary <?php if ($rows[0]['Private'] == 1) {echo "active";} ?>">
                            <input class="form-check-input" type="checkbox" autocomplete="off" id="inputPrivateCheck" <?php if ($rows[0]['Private'] == 1) {echo " checked=\"checked\"";} ?>>
                            <span>Privato</span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="inputNote">Note</label>
                <textarea class="form-control" id="inputNote" rows="3" placeholder="Note">
                <?php echo $rows[0]['Note']; ?>
                </textarea>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit" id="edit-customer-save">Save</button>
                <button class="btn btn-primary" type="reset" id="edit-customer-reset">Reset</button>
            </div>

            <div class="alert alert-success d-none" role="alert" id="edit-customer-success">
                <i class="fas fa-check"></i>&nbsp;Customer/Supplier edited with success!
            </div>
            
            <div class="alert alert-danger d-none" role="alert" id="edit-customer-error">
			&nbsp;
            </div>
            
            <div class="alert alert-primary d-none" role="alert" id="edit-customer-loading">
                <i class="fas fa-spinner fa-spin"></i>&nbsp;Loading...
            </div>
        </form>
    </div>
</div>
<?php
}
else
{
    echo "<div class=\"alert alert-danger\" role=\"alert\">\n";
    echo "\t<h4 class=\"alert-heading\">Ops...</h4>\n";
    echo "\t<p>Server Error: Service not found!</p>\n";
    echo "</div>";
}
?>