<!-- Page Heading -->
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Clienti &amp; Fornitori</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a class="btn btn-sm btn-outline-primary" href="<?php echo $baseUrl;?>/records/customersupplier/list" role="button"><i class="fas fa-arrow-left"></i>&nbsp;Back</a>
        </div>
    </div>
</div>

<?php

$isError = FALSE;

if ($nav->getResourceId() == 0)
{
    // TODO: print error
}
else 
{
    // Get the user list
    $query = "SELECT * FROM " . PRJ_DB_TABLE_CUSTOMER_SUPPLIER . " WHERE Id={$nav->getResourceId()}";
    $result = $db->query($query);
    if ($result)
    {
        $rows = $result->fetchAll(PDO::FETCH_ASSOC);
        if ((count($rows) == 0) || (count($rows) > 1))
        {
            $isError = TRUE;
        }
    }
    else 
    {
        $isError = TRUE;
    }
}

if ($isError == FALSE)
{
?>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-building"></i>
        Modifica Cliente/Fornitore
    </div>
    <div class="card-body">
<?php 
$type = "edit";
include('prjformview/customersupplier.form.phtml');
?>
    </div>
</div>
<?php
}
else
{
    echo "<div class=\"alert alert-danger\" role=\"alert\">\n";
    echo "\t<h4 class=\"alert-heading\">Ops...</h4>\n";
    echo "\t<p>Server Error: Service not found!</p>\n";
    echo "</div>";
}
?>