<!-- Page Heading -->
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Clienti &amp; Fornitori</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a class="btn btn-sm btn-outline-primary" href="<?php echo $baseUrl;?>/records/customersupplier/add" role="button"><i class="fas fa-plus-square"></i>&nbsp;Add</a>
        </div>
    </div>
</div>

<?php
/*
// Get the manufacturer list
$query = "SELECT * FROM User ORDER BY Surname";
$result = $db->query($query);
if ($result)
{
    $rows = $result->fetchAll(PDO::FETCH_ASSOC);
    if ($rows)
    {
        echo "<div class=\"table-responsive\">\n";
        echo "\t<table id=\"user-list-table\" class=\"table table-striped table-bordered\" style=\"width:100%\">\n";
        echo "\t\t<thead>\n";
        echo "\t\t\t<tr>\n";
        echo "\t\t\t\t<th>Nome</th>\n";
        echo "\t\t\t\t<th>Username</th>\n";
        echo "\t\t\t\t<th>Email</th>\n";
        echo "\t\t\t\t<th>&nbsp;</th>\n";
        echo "\t\t\t</tr>\n";
        echo "\t\t</thead>\n";
        echo "\t\t<tbody>\n";
        
        // Scan the DB elements
        foreach ($rows as $row)
        {
            echo "\t\t\t<tr>\n";
            echo "\t\t\t\t<td>{$row['Surname']} {$row['Name']}</td>\n";
            echo "\t\t\t\t<td>{$row['Username']}</td>\n";
            echo "\t\t\t\t<td>{$row['Email']}</td>\n";
            echo "\t\t\t\t<td>";
            echo "<div class=\"btn-group\" role=\"group\" aria-label=\"Commands\">";
            echo "<a class=\"btn btn-primary btn-sm\" href=\"{$baseUrl}/records/employee/view/{$row['Id']}\" role=\"button\"><i class=\"fas fa-eye\"></i></a>";
            echo "<a class=\"btn btn-primary btn-sm\" href=\"{$baseUrl}/records/employee/edit/{$row['Id']}\" role=\"button\"><i class=\"fas fa-edit\"></i></a>";
            echo "<a class=\"btn btn-primary btn-sm\" href=\"{$baseUrl}/records/employee/delete/{$row['Id']}\" role=\"button\"><i class=\"far fa-trash-alt\"></i></a>";
            echo "</div>";
            echo "</td>\n";
            echo "\t\t\t</tr>\n";
        }
        
        echo "\t\t</tbody>\n";
        echo "\t</table>\n";
        echo "</div>\n";
    }
//     else 
//     {
    
//     }
}*/
?>