<!-- Page Heading -->
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Clienti &amp; Fornitori</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a class="btn btn-sm btn-outline-primary" href="<?php echo $baseUrl;?>/records/customersupplier/add" role="button"><i class="fas fa-plus-square"></i>&nbsp;Add</a>
        </div>
    </div>
</div>

<?php

// Get the manufacturer list
$query = "SELECT * FROM " . PRJ_DB_TABLE_CUSTOMER_SUPPLIER . " ORDER BY Name";
$result = $db->query($query);
if ($result)
{
    $rows = $result->fetchAll(PDO::FETCH_ASSOC);
    if ($rows)
    {
        echo "<div class=\"table-responsive\">\n";
        echo "\t<table id=\"customer-list-table\" class=\"table table-striped table-bordered\" style=\"width:100%\">\n";
        echo "\t\t<thead>\n";
        echo "\t\t\t<tr>\n";
        echo "\t\t\t\t<th>LTCode</th>\n";
        echo "\t\t\t\t<th>Nome</th>\n";
        echo "\t\t\t\t<th>Indirizzo</th>\n";
        echo "\t\t\t\t<th>VAT-ID </th>\n";
        echo "\t\t\t\t<th>&nbsp;</th>\n";
        echo "\t\t\t</tr>\n";
        echo "\t\t</thead>\n";
        echo "\t\t<tbody>\n";
        
        // Scan the DB elements
        foreach ($rows as $row)
        {
            echo "\t\t\t<tr>\n";
            // Print LT-Code
            echo "\t\t\t\t<td>{$row['Code']}</td>\n";
            // Print company name with user or company icon.
            echo "\t\t\t\t<td>";
            if (1 == $row['Private'])
                echo "<span class=\"btn btn-primary btn-sm\"><i class=\"fas fa-user\"></i></span>";
            else
                echo "<span class=\"btn btn-primary btn-sm\"><i class=\"fas fa-building\"></i></span>";
            echo " {$row['Name']}</td>\n";
            // Print address
            echo "\t\t\t\t<td>{$row['Address']}, {$row['ZipCode']} {$row['City']} ({$row['District']}), {$row['Country']}</td>\n";
            echo "\t\t\t\t<td>";
            // Print VATID/NIN
            if (1 == $row['Private'])
                echo $row['NIN'];
            else
                echo $row['VATID'];
            echo "</td>\n";
            echo "\t\t\t\t<td>";
            echo "<div class=\"btn-group\" role=\"group\" aria-label=\"Commands\">";
            echo "<a class=\"btn btn-primary btn-sm\" href=\"{$baseUrl}/records/customersupplier/view/{$row['Id']}\" role=\"button\"><i class=\"fas fa-eye\"></i></a>";
            echo "<a class=\"btn btn-primary btn-sm\" href=\"{$baseUrl}/records/customersupplier/edit/{$row['Id']}\" role=\"button\"><i class=\"fas fa-edit\"></i></a>";
            echo "<a class=\"btn btn-primary btn-sm\" href=\"{$baseUrl}/records/customersupplier/delete/{$row['Id']}\" role=\"button\"><i class=\"far fa-trash-alt\"></i></a>";
            echo "</div>";
            echo "</td>\n";
            echo "\t\t\t</tr>\n";
        }
        
        echo "\t\t</tbody>\n";
        echo "\t</table>\n";
        echo "</div>\n";
    }
    else 
    {
        echo "<div class=\"alert alert-warning\" role=\"alert\">\n";
        echo "\t<h4 class=\"alert-heading\">No Elements</h4>\n";
        echo "\t<p>Warning: No elements found!</p>\n";
        echo "</div>";
    }
}
else
{
    echo "<div class=\"alert alert-danger\" role=\"alert\">\n";
    echo "\t<h4 class=\"alert-heading\">Database Error</h4>\n";
    echo "\t<p>Error: Database not reply!</p>\n";
    echo "</div>";
}
?>