<!-- Page Heading -->
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Clienti &amp; Fornitori</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a class="btn btn-sm btn-outline-primary" href="<?php echo $baseUrl;?>/records/customersupplier/list" role="button"><i class="fas fa-arrow-left"></i>&nbsp;Back</a>
        </div>
    </div>
</div>

<?php

$isError = FALSE;

if ($nav->getResourceId() == 0)
{
    // TODO: print error
}
else 
{
    // Get the user list
    $query = "SELECT * FROM " . PRJ_DB_TABLE_CUSTOMER_SUPPLIER . " WHERE Id={$nav->getResourceId()}";
    $result = $db->query($query);
    if ($result)
    {
        $rows = $result->fetchAll(PDO::FETCH_ASSOC);
        if ((count($rows) == 0) || (count($rows) > 1))
        {
            $isError = TRUE;
        }
    }
    else 
    {
        $isError = TRUE;
    }
}

if ($isError == FALSE)
{
?>
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-building"></i>
        Visualizza Cliente/Fornitore
    </div>
    <div class="card-body">
        <form>
        <div class="form-row">
                <div class="form-group col-md-2">
                    <label for="inputCode">Code</label>
                    <input type="text" class="form-control" id="inputCode" placeholder="<?php echo $rows[0]['Code']; ?>" disabled>
                </div>
                <div class="form-group col-md-10">
                    <label for="inputName">Nome Azienda</label>
                    <input type="text" class="form-control" id="inputName" placeholder="<?php echo $rows[0]['Name']; ?>" disabled>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputAddress">Indirizzo</label>
                    <input type="text" class="form-control" id="inputAddress" placeholder="<?php echo $rows[0]['Address']; ?>" disabled>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputCity">Città</label>
                    <input type="text" class="form-control" id="inputCity" placeholder="<?php echo $rows[0]['City']; ?>" disabled>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="inputDistrict">Provincia (Sigla)</label>
                    <input type="text" class="form-control" id="inputDistrict" placeholder="<?php echo $rows[0]['District']; ?>" disabled>
                </div>
                <div class="form-group col-md-4">
                    <label for="inputZip">CAP</label>
                    <input type="text" class="form-control" id="inputZip" placeholder="<?php echo $rows[0]['ZipCode']; ?>" disabled>
                </div>
                <div class="form-group col-md-4">
                    <label for="inputCountry">Paese</label>
                    <input type="text" class="form-control" id="inputCountry" placeholder="<?php echo $rows[0]['Country']; ?>" disabled> 
                </div>
            </div>
            <div class="form-row">
                 <div class="form-group col-md-6">
          	         <label for="inputEmail">Email</label>
                     <input type="email" class="form-control" id="inputEmail" placeholder="<?php echo $rows[0]['Email']; ?>" disabled>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputWebsite">Website</label>
                    <input type="text" class="form-control" id="inputWebsite" placeholder="<?php echo $rows[0]['Website']; ?>" disabled>
                </div>
            </div>
            <div class="form-row">
            <div class="form-group col-md-6">
                    <label for="inputPhone">Telefono</label>
                    <input type="text" class="form-control" id="inputPhone" placeholder="<?php echo $rows[0]['Phone']; ?>" disabled>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputFax">Fax</label>
                    <input type="text" class="form-control" id="inputFax" placeholder="<?php echo $rows[0]['Fax']; ?>" disabled>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputVAT">P. IVA</label>
                    <input type="text" class="form-control" id="inputVAT" placeholder="<?php echo $rows[0]['VATID']; ?>" disabled>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputNIN">Codice Fiscale</label>
                    <input type="text" class="form-control" id="inputNIN" placeholder="<?php echo $rows[0]['NIN']; ?>" disabled>
                </div>
            </div>
            <div class="form-group">
                <label for="inputIBAN">IBAN</label>
                <input type="text" class="form-control" id="inputIBAN" placeholder="<?php echo $rows[0]['IBAN']; ?>" disabled>
            </div>
            <div class="form-row">
                <div class="form-group col-md-1">
                    <label for="inputStatus">Status</label>
                    <div class="btn-group-toggle"  data-toggle="buttons">
                        <label class="btn form-check-label <?php if ($rows[0]['Active'] == 1) {echo "btn-primary active";} else {echo "btn-default";} ?> ">
                            <input class="form-check-input" type="checkbox" autocomplete="off" id="inputStatus" disabled> 
                            <span>Attivo</span>
                        </label>
                    </div>
                </div>
                <div class="form-group col-md-11">
                    <label for="inputCustomerCheck">Opzioni</label>
                    <div class="btn-group-toggle"  data-toggle="buttons">
                        <label class="btn form-check-label <?php if ($rows[0]['Customer'] == 1) {echo "btn-primary active";} else {echo "btn-secondary";} ?> ">
                            <input class="form-check-input" type="checkbox" autocomplete="off" id="inputCustomerCheck" disabled> 
                            <span>Cliente</span>
                        </label>
                        <label class="btn form-check-label <?php if ($rows[0]['Supplier'] == 1)  {echo "btn-primary active";} else {echo "btn-secondary";} ?> ">
                            <input class="form-check-input" type="checkbox" autocomplete="off" id="inputSupplierCheck" disabled>
                            <span>Fornitore</span>
                        </label>
                        <label class="btn form-check-label <?php if ($rows[0]['Private'] == 1)  {echo "btn-primary active";} else {echo "btn-secondary";} ?> ">
                            <input class="form-check-input" type="checkbox" autocomplete="off" id="inputPrivateCheck" disabled>
                            <span>Privato</span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="inputNote">Note</label>
                <textarea class="form-control" id="inputNote" rows="3" placeholder="<?php echo $rows[0]['Note']; ?>" disabled>
                </textarea>
            </div>
        </form>
    </div>
</div>
<?php
}
else
{
    echo "<div class=\"alert alert-danger\" role=\"alert\">\n";
    echo "\t<h4 class=\"alert-heading\">Ops...</h4>\n";
    echo "\t<p>Server Error: Service not found!</p>\n";
    echo "</div>";
}
?>