        
        </div> <!-- Close #wrapper -->
        
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?php echo $baseUrl;?>/scripts/jquery/jquery-3.3.1.slim.min.js"><\/script>')</script>
        <script type="text/javascript" src="<?php echo $baseUrl;?>/scripts/bootstrap/js/bootstrap.bundle.min.js"></script>

    </body>
</html>