        <footer class="footer">
            <div class="container">
                <p class="text-muted">
<?php 
                echo $prjName." ".$prjVersion." - (C) ".$prjAuthor;
?>
				</p>
            </div>
        </footer>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?php echo $baseUrl;?>/scripts/jquery/jquery-1.12.0.min.js"><\/script>')</script>
        <script src="<?php echo $baseUrl;?>/scripts/bootstrap/js/bootstrap.min.js"></script>
    </body>
</html>