        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script>window.jQuery || document.write('<script src="<?php echo $baseUrl;?>/scripts/jquery/jquery-3.3.1.slim.min.js"><\/script>')</script>
        <script type="text/javascript" src="<?php echo $baseUrl;?>/scripts/bootstrap/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    </body>
</html>