<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
<?php 
        echo PRJ_NAME." ".PRJ_VERSION;
        if (!empty($pageTitle)) echo " - ".$pageTitle;
?>
        </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
                <!-- Bootstrap core CSS -->
        <link href="/scripts/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        
        <!-- Custom styles for this template -->
        <link rel="stylesheet" href="/styles/labortool.css">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
    