    <nav class="navbar navbar-expand navbar-dark bg-dark static-top shadow">
        <a class="navbar-brand mr-1" href=""<?php echo $baseUrl."/home";?>"><?php echo PRJ_NAME." ".PRJ_VERSION; ?></a>
    </nav>

    <div id="wrapper">
        <ul class="sidebar navbar-nav">
<?php 

    for ($i = 0; $i < count($this->_sidebar); $i++)
    {
        $active = ($this->_sidebar[$i]['active']) ? 'active' : '';
        
        if (count($this->_sidebar[$i]['sub']) > 0)
        {
            echo "<li class=\"nav-item dropdown\">\n";
            echo "<a class=\"nav-link {$active} dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\" id=\"{$this->_sidebar[$i]['id']}\" aria-haspopup=\"true\" aria-expanded=\"false\" role=\"button\">\n";
            echo "<i class=\"{$this->_sidebar[$i]['logo']} nav-logo\"></i>\n";
            echo "<span>{$this->_sidebar[$i]['name']}</span>\n</a>\n";
            
            echo "<div class=\"dropdown-menu\" aria-labelledby=\"{$this->_sidebar[$i]['id']}\">\n";
            for ($y = 0; $y < count($this->_sidebar[$i]['sub']); $y++)
            {
                echo "<a class=\"dropdown-item\" href=\"{$baseUrl}/{$this->_sidebar[$i]['sub'][$y]['url']}\">{$this->_sidebar[$i]['sub'][$y]['name']}</a>\n";
            }
            echo "</div>\n</li>\n";
        }
        else
        {
            echo "<li class=\"nav-item\">\n";
            echo "<a class=\"nav-link {$active}\" href=\"{$baseUrl}/{$this->_sidebar[$i]['url']}\" title=\"{$this->_sidebar[$i]['title']}\">\n";
            echo "<i class=\"{$this->_sidebar[$i]['logo']} nav-logo\"></i>\n";
            echo "<span>{$this->_sidebar[$i]['name']}</span>\n</a>\n</li>\n";
        }
    }
?>   
        </ul>