    <nav class="navbar navbar-expand navbar-dark bg-dark static-top shadow">
        <a class="navbar-brand mr-1" href="<?php echo $baseUrl;?>/home"><?php echo PRJ_NAME." ".PRJ_VERSION; ?></a>

        <span class="navbar-user ml-auto mr-1">
<?php
    echo "Benvenuto &nbsp;<b>" . $user['Name'] . " " . $user['Surname'] . "</b>"
?>
        </span>

        <ul class="navbar-nav ml-1 mr-0">
            <li class="nav-item no-arrow">
                <a id="labortool-logout" class="nav-link" href="#" alt="LogOut" role="button">
                    <i class="fas fa-sign-out-alt"></i>
                </a>
            </li>
        </ul>

        <!-- maybe one times...
        <ul class="navbar-nav ml-1 mr-0">
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-cog"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
                </div>
            </li>
        </ul>
        -->
    </nav>

    <div id="wrapper">
        <ul class="sidebar navbar-nav">
<?php 

    for ($i = 0; $i < count($this->_sidebar); $i++)
    {
        $active = ($this->_sidebar[$i]['active']) ? 'active' : '';
        
        if (count($this->_sidebar[$i]['sub']) > 0)
        {
            echo "<li class=\"nav-item dropdown\">\n";
            echo "<a class=\"nav-link {$active} dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\" id=\"{$this->_sidebar[$i]['id']}\" aria-haspopup=\"true\" aria-expanded=\"false\" role=\"button\">\n";
            echo "<i class=\"{$this->_sidebar[$i]['logo']} nav-logo\"></i>\n";
            echo "<span>{$this->_sidebar[$i]['name']}</span>\n</a>\n";
            
            echo "<div class=\"dropdown-menu\" aria-labelledby=\"{$this->_sidebar[$i]['id']}\">\n";
            for ($y = 0; $y < count($this->_sidebar[$i]['sub']); $y++)
            {
                echo "<a class=\"dropdown-item\" href=\"{$baseUrl}/{$this->_sidebar[$i]['sub'][$y]['url']}\">{$this->_sidebar[$i]['sub'][$y]['name']}</a>\n";
            }
            echo "</div>\n</li>\n";
        }
        else
        {
            echo "<li class=\"nav-item\">\n";
            echo "<a class=\"nav-link {$active}\" href=\"{$baseUrl}/{$this->_sidebar[$i]['url']}\" title=\"{$this->_sidebar[$i]['title']}\">\n";
            echo "<i class=\"{$this->_sidebar[$i]['logo']} nav-logo\"></i>\n";
            echo "<span>{$this->_sidebar[$i]['name']}</span>\n</a>\n</li>\n";
        }
    }
?>   
        </ul>