    <nav class="navbar navbar-expand navbar-dark bg-dark static-top shadow">
        <a class="navbar-brand mr-1" href=""<?php echo $baseUrl."/home";?>"><?php echo PRJ_NAME." ".PRJ_VERSION; ?></a>
    </nav>

    <div id="wrapper">
        <ul class="sidebar navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $baseUrl."/home";?>">
                    <i class="fas fa-tachometer-alt nav-logo"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="anagrafiche" aria-haspopup="true" aria-expanded="false" role="button">
                    <i class="fas fa-microchip nav-logo"></i>
                    <span>Anagrafiche</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="anagrafiche">
                    <a class="dropdown-item" href="<?php echo $baseUrl."/records/article";?>">Articoli</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/records/customer-supplier";?>">Clienti/Fornitori</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/records/manufacturer";?>">Produttori</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/records/employee";?>">Collaboratori</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="gestione" aria-haspopup="true" aria-expanded="false" role="button">
                    <i class="far fa-calendar-alt nav-logo"></i>
                    <span>Gestione</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="gestione">
                    <a class="dropdown-item" href="<?php echo $baseUrl."/management/project";?>">Progetti</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/management/board";?>">Schede Elettroniche</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/management/activity";?>">Attività</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/management/production";?>">Produzioni</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="magazzino" aria-haspopup="true" aria-expanded="false" role="button">
                    <i class="fas fa-warehouse nav-logo"></i>
                    <span>Magazzino</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="magazzino">
                    <a class="dropdown-item" href="<?php echo $baseUrl."/warehouse/status";?>">Status</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/management/movements";?>">Carico/Scarico</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/management/inventory";?>">Inventario</a>
                </div>
            </li>

        	    <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="vendite" aria-haspopup="true" aria-expanded="false" role="button">
                    <i class="far fa-money-bill-alt nav-logo"></i>
                    <span>Vendite</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="vendite">
                    <a class="dropdown-item" href="<?php echo $baseUrl."/sales/offer";?>">Offerte</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/sales/order";?>">Ordini</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/sales/transport-document";?>">DDT</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/sales/invoice";?>">Fatture</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="acquisti" aria-haspopup="true" aria-expanded="false" role="button">
                    <i class="fas fa-cart-arrow-down nav-logo"></i>
                    <span>Acquisti</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="acquisti">
                    <a class="dropdown-item" href="<?php echo $baseUrl."/purchases/order";?>">Ordini</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/purchases/transport-document";?>">DDT</a>
                    <a class="dropdown-item" href="<?php echo $baseUrl."/purchases/invoice";?>">Fatture</a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="<?php echo $baseUrl."/report";?>">
                    <i class="fas fa-chart-line nav-logo"></i>
                    <span>Report</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="<?php echo $baseUrl."/about";?>">
                    <i class="far fa-question-circle nav-logo"></i>
                    <span>About</span>
                </a>
            </li> 
        </ul>
